site_name: My Docs

plugins:
    - search
    - markmap
    - bibtex:
        bib_file: docs/references.bib
        csl_file: docs/ieee.csl

markdown_extensions:
    - footnotes
    - pymdownx.caret
    - attr_list
    - md_in_html
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - MindMap: mindmap.md
    - Readout Electronics:
        - Aquisition Hardware: readout_electronics/aquisition-hardware.md
        - Readout Channels: readout_electronics/channels.md
        - SiPMs: readout_electronics/sipms.md
    - Sensitive Elements:
        - Geometry: sensitive_elements/geometry.md
        
        - Scintillation Material: sensitive_elements/scintillation-material.md
    - Performance Enhancements:
        - DOI Encoding: performance_enhancements/doi-encoding.md
        - Time Of Flight: performance_enhancements/time-of-flight.md
        - Performance: performance_enhancements/performance.md