site_name: My Docs

plugins:
    - search
    - markmap
    - bibtex:
        bib_file: docs/references.bib
        csl_file: docs/ieee.csl

markdown_extensions:
    - footnotes
    - pymdownx.caret
    - attr_list
    - md_in_html

nav:
    - Home: index.md
    - MindMap: mindmap.md
    - Readout Electronics:
        - Aquisition Hardware: docs/readout_electronics/aquisition-hardware.md
        - Readout Channels: docs/readout_electronics/channels.md
        - SiPMs: docs/readout_electronics/sipms.md
    - Sensitive Elements:
        - Geometry: docs/sensitive_elements/geometry.md
        - DOI Encoding: docs/sensitive_elements/doi_encoding.md
        - Scintillation Material: docs/sensitive_elements/scintillation-material.md