site_name: My Docs

plugins:
    - search
    - markmap
    - bibtex:
        bib_file: docs/references.bib
        csl_file: docs/ieee.csl

markdown_extensions:
    - footnotes
    - pymdownx.caret
    - attr_list
    - md_in_html

nav:
  - Home: index.md
  - Readout Channels: readout-channels.md